# Copyright 2015 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/python/runtime
# for details.

# Last Deploy: 2020-12-08 11:03 AM

# [START runtime]
runtime: python27
api_version: 1
threadsafe: true

instance_class: F2

handlers:
- url: /sitemap.xml
  static_files: static/sitemap.xml
  upload: static/sitemap.xml
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /robots.txt
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
- url: /static
  static_dir: static
- url: /images
  static_dir: images
- url: /LRP.*
  script: LRP.app
  secure: always
- url: .*
  script: LRP.app
  secure: always

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webob
  version: "1.1.1"
- name: MySQLdb
  version: "latest"
- name: webapp2
  version: "2.5.2"
- name: PIL
  version: latest
- name: ssl
  version: latest

builtins:
 - deferred: on


